apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ryanj3-poi-backend-app-dev
  annotations:
    argocd/app-name: ryanj3-poi-backend-app-dev
    backstage.io/kubernetes-id: ryanj3-poi-backend-app-dev
    backstage.io/kubernetes-namespace: ryanj3
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=ryanj3-poi-backend-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23JanusN/ryanj3-backend
  tags:
    - java
    - quarkus
    - maven
    - workshop
  links:
    - url: https://console-openshift-console.apps.summit23bis.17gd.p1.openshiftapps.com/dev-pipelines/ns/ryanj3/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.summit23bis.17gd.p1.openshiftapps.com/k8s/ns/ryanj3/deployments/poi-backend-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.summit23bis.17gd.p1.openshiftapps.com/#https://github.com/Summit23JanusN/ryanj3-backend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:ryanj"
  system: workshop-system-ryanj3
  providesApis:
    - backend-api-ryanj3
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-ryanj3
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:ryanj"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backend-api-ryanj3
  description: API surface used by workshop attendees to initialize and load parks data
  links:
    - url: http://poi-backend-app-ryanj3.apps.summit23bis.17gd.p1.openshiftapps.com/q/swagger-ui
      title: Swagger UI
      icon: web
    - url: https://github.com/Summit23JanusN/ryanj3-backend/tree/main/src/main/resources/META-INF/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: "user:ryanj"
  system: workshop-system-ryanj3
  definition:
    $text: https://github.com/Summit23JanusN/ryanj3-backend/tree/main/src/main/resources/META-INF/openapi.yaml
